insert into announcements (title, authors, body, thumbnail_id)
values ('Mga Paskil sa Palaro', '{"G. Dela Cruz", "G. Reyes"}',
        'Mga paskil para sa mga palaro ngayong taon.',
        'srsths-backdrop_thcdy4'),
       ('Mga Paskil sa Buwan ng Wika', '{"G. Dela Cruz", "G. Reyes"}',
        'Mga paskil para sa Buwan ng Wika ngayong taon.',
        'srsths-backdrop_thcdy4'),
       ('Mga Paskil sa Buwan ng Nutrisyon', '{"G. Dela Cruz", "G. Reyes"}',
        'Mga paskil para sa Buwan ng Nutrisyon ngayong taon.',
        'srsths-backdrop_thcdy4'),
       ('Mga Paskil sa Buwan ng Kasaysayan', '{"G. Dela Cruz", "G. Reyes"}',
        'Mga paskil para sa Buwan ng Kasaysayan ngayong taon.',
        'srsths-backdrop_thcdy4'),
       ('Mga Paskil sa Buwan ng Kalikasan', '{"G. Dela Cruz", "G. Reyes"}',
        'Mga paskil para sa Buwan ng Kalikasan ngayong taon.',
        'srsths-backdrop_thcdy4'),
       ('Mga Paskil sa Buwan ng Kabataan', '{"G. Dela Cruz", "G. Reyes"}',
        'Mga paskil para sa Buwan ng Kabataan ngayong taon.',
        'srsths-backdrop_thcdy4'),
       ('Mga Paskil sa Buwan ng Kasuotang Filipino',
        '{"G. Dela Cruz", "G. Reyes"}',
        'Mga paskil para sa Buwan ng Kasuotang Filipino ngayong taon.',
        'srsths-backdrop_thcdy4'),
       ('Mga Paskil sa Buwan ng Kalusugan', '{"G. Dela Cruz", "G. Reyes"}', 'Mga
     paskil para sa Buwan ng Kalusugan ngayong taon.', 'srsths-backdrop_thcdy4')